#!/bin/sh

BASE_DIR_PATH=$(cd -- $(dirname $0)/../ && pwd -P)

. $BASE_DIR_PATH/functions

if ! has_binary npm; then
  try_sourcing_nvm
fi

if ! has_binary npm; then
  printf "Can't find npm. Quitting...\n"
  exit 1
fi

COMMIT_EDITMSG_PATH="$(pwd)/$1"

(cd "$BASE_DIR_PATH" && npx --no -- commitlint --edit "$COMMIT_EDITMSG_PATH")
